# 忽略的坐标（格式：世界名,x,y,z）
ignore-commandblocks:
  - "world_nether,100,50,-200"
  - "my_world,123,64,456"

# 命令合并配置
command-merge:
  window: 3000    # 合并时间窗口（毫秒）
  max-count: 10   # 最大合并次数

# 日志轮转配置
log-rotate:
  keep-days: 7    # 保留日志天数
